// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOYzoovbOMahzHoFxxAJRk0DUTj5XaMyI',
    appId: '1:102037705574:web:1fdf4df63cc10f3a922ea7',
    messagingSenderId: '102037705574',
    projectId: 'talent-tourney',
    authDomain: 'talent-tourney.firebaseapp.com',
    storageBucket: 'talent-tourney.appspot.com',
    measurementId: 'G-9NKPZ4435F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-I3wkVHf7gU8VOLMNukrB1I2c5OYpp6o',
    appId: '1:102037705574:android:b65cf5db7b87c8d3922ea7',
    messagingSenderId: '102037705574',
    projectId: 'talent-tourney',
    storageBucket: 'talent-tourney.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRKHjtxmW_YMskI8JSGX_kTFEHKUDHLIM',
    appId: '1:102037705574:ios:249768736c9382a2922ea7',
    messagingSenderId: '102037705574',
    projectId: 'talent-tourney',
    storageBucket: 'talent-tourney.appspot.com',
    iosClientId:
        '102037705574-5960j9fd5ha5p0tvuchui4i1svc54ja6.apps.googleusercontent.com',
    iosBundleId: 'com.example.talentTourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRKHjtxmW_YMskI8JSGX_kTFEHKUDHLIM',
    appId: '1:102037705574:ios:75606a8b3ed0e06c922ea7',
    messagingSenderId: '102037705574',
    projectId: 'talent-tourney',
    storageBucket: 'talent-tourney.appspot.com',
    iosClientId:
        '102037705574-0jvke77uh400g9or9v2i0u120cp8md6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.talentTourney.RunnerTests',
  );
}
